### PR TITLE
Yuanming leee patch 1

### PR DESCRIPTION
**Pull request by YuanmingLeee**

### CODE REVIEW

**Comment by ZaynJarvis** [comment]
[refer here](https://github.com/yarnpkg/yarn/issues/1583)
We may leave it as it is for now.

**Comment by YuanmingLeee** [comment]
without that, the website works fine, so, just feel free to remove.

**Comment by ZaynJarvis** [comment]
Since our CI platform Netlify are using yarn install. in case we don't have a yarn lock to specify the exact version of packages, there may result into serious problems that occur in different machines.
Therefore, even though we don't see any errors for now, I do recommend adding one lock file inside.
We are not using package-lock.json tho, cuz I recommend using yarn instead.
However, this can be purely a personal preference, using npm install won't affect the packages as well.

**Comment by YuanmingLeee** [comment]
> Since our CI platform Netlify are using yarn install. in case we don't have a yarn lock to specify the exact version of packages, there may result into serious problems that occur in different machines.
> Therefore, even though we don't see any errors for now, I do recommend adding one lock file inside.
> We are not using package-lock.json tho, cuz I recommend using yarn instead.
> However, this can be purely a personal preference, using npm install won't affect the packages as well.
yarn.lock and package-lock.json are auto-generated file. If you use yarn install or npm install, it won't have any issue in configuration, as long as you have package.json

**Review by ZaynJarvis — COMMENTED** [review]
Take note here.
```json
"lint-staged": {
    "*.{js,css,md}": [
      "yarn run lint",
      "yarn run lint:css",
      "git add --force"
    ]
  },
```

If we are not adding yarn.lock. Netlify will not install yarn and use npm install instead. (Maybe, need investigation on this ) This will be the reason why this script is not passing the build. In deploy site it specifies 
```bash
12:57:47 PM: Executing user command: yarn build
12:57:47 PM: /usr/local/bin/build: line 32: yarn: command not found
12:57:47 PM: failed during stage 'building site': Build script returned non-zero exit code: 127
12:57:47 PM: Caching artifacts
12:57:47 PM: Started saving node modules
12:57:47 PM: Finished saving node modules
12:57:47 PM: Shutting down logging, 13 messages pending
```

**Comment by YuanmingLeee** [comment]
just put yarn in "dependencies"?
u can try and see, as I also run into this problem and it fixes when I manually install yarn

**Pull request closed without merging**
